Store summary cr objects
kubescape/kubevuln pull request #141
Opened 2023-08-16 15:22 UTC by rcohencyberarmor

2023-08-16 15:25 UTC, matthyx requested changes

2023-08-16 15:25 UTC, matthyx commented on repositories/apiserver.go
> +		return "", nil
Please document why no error

2023-08-17 06:52 UTC, rcohencyberarmor commented on repositories/apiserver.go
> +		return "", nil
correct it

2023-08-17 08:34 UTC, matthyx approved these changes

2023-08-17 08:42 UTC, merged